package view;

import Services.ClienteServices;
import Services.LivroServices;
import Services.ServicesFactory;
import Services.VendaLivroServices;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Cliente;
import model.Livro;
import model.VendaLivro;

/**
 *
 * @author alexandreluis
 */
public class jfCompraVenda extends javax.swing.JFrame
{

    private Double valorFinal = 0.0;

    /**
     * Creates new form jfCompraVenda
     */
    public jfCompraVenda()
    {
        initComponents();
        addRowToTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jtfDocCliente = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jtfDocLivro = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jtfSubTotal = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jtfQuantidade = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jlValorUnidade = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jlData = new javax.swing.JLabel();
        jlCliente = new javax.swing.JLabel();
        jlLivro = new javax.swing.JLabel();
        jbClienteOk = new javax.swing.JButton();
        jbIsbnOk = new javax.swing.JButton();
        jbCalcular = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtListaCompraVenda = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("CPF/CNPJ");

        jtfDocCliente.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jtfDocClienteActionPerformed(evt);
            }
        });

        jLabel2.setText("ISBN");

        jLabel3.setText(" ");

        jLabel4.setText("Quantidade");

        jLabel6.setText("Valor Total");

        jLabel7.setText("Valor Unidade");

        jlValorUnidade.setText(" ");

        jButton1.setText("Comprar");
        jButton1.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel9.setText(" ");

        jLabel5.setText("Data");

        jlData.setText(" ");

        jlCliente.setText("ClienteOK?");

        jlLivro.setText("LivroOK?");

        jbClienteOk.setText("Ok?");
        jbClienteOk.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jbClienteOkActionPerformed(evt);
            }
        });

        jbIsbnOk.setText("Ok?");
        jbIsbnOk.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jbIsbnOkActionPerformed(evt);
            }
        });

        jbCalcular.setText("Calular");
        jbCalcular.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jbCalcularActionPerformed(evt);
            }
        });

        jLabel8.setText("Venda de Livro");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addComponent(jlValorUnidade, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addGap(60, 60, 60)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jtfDocCliente)
                            .addComponent(jtfDocLivro, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jlCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jlLivro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jbClienteOk)
                            .addComponent(jbIsbnOk))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton1)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel6))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jtfSubTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jtfQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 268, Short.MAX_VALUE)
                                .addComponent(jLabel5)
                                .addGap(18, 18, 18)
                                .addComponent(jlData, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(2, 2, 2))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(36, 36, 36)
                                .addComponent(jbCalcular)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel8)
                .addGap(7, 7, 7)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jtfDocCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(jlCliente)
                    .addComponent(jbClienteOk))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jtfDocLivro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jlLivro)
                    .addComponent(jbIsbnOk))
                .addGap(52, 52, 52)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jlValorUnidade))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jtfQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jlData))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jtfSubTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbCalcular))
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap(49, Short.MAX_VALUE))
        );

        jtListaCompraVenda.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][]
            {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String []
            {
                "idVendaLivro", "idCliente", "idLivro", "Qtd", "SubTotal", "Data"
            }
        )
        {
            Class[] types = new Class []
            {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Double.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean []
            {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex)
            {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex)
            {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jtListaCompraVenda);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        ClienteServices clienteServices = ServicesFactory.getClienteServices();
        LivroServices livroServices = ServicesFactory.getLivroServices();

        LocalDate today = LocalDate.now();
        String data = today.toString();

        if (jtfDocCliente.getText().equals(""))
        {
            JOptionPane.showInputDialog(null, "Preencha o CPF/CNPJ");
        }

        if (jtfDocLivro.getText().equals(""))
        {
            JOptionPane.showInputDialog(null, "Preencha o ISBN.");
        }

        if (jtfQuantidade.getText().equals(""))
        {
            JOptionPane.showInputDialog(null, "Preencha a quantidade.");
        }

        try
        {
            Cliente cliente = clienteServices.getByDoc(jtfDocCliente.getText());
            Livro livro = livroServices.getByDoc(jtfDocLivro.getText());

            jlValorUnidade.setText("" + livro.getPreco());
            jlData.setText(today.toString());

            VendaLivro vendaLivro = new VendaLivro();
            vendaLivro.setIdCliente(cliente.getIdCliente());
            vendaLivro.setIdLivro(livro.getIdLivro());
            vendaLivro.setQtd(Integer.parseInt(jtfQuantidade.getText()));
            vendaLivro.setSubTotal(Double.parseDouble(jtfSubTotal.getText()));

            DateFormat formatter = new SimpleDateFormat("yyyy-MM-dd");

            Date myDate = formatter.parse(data);
            java.sql.Date sqlDate = new java.sql.Date(myDate.getTime());
            vendaLivro.setDataVenda(sqlDate);

            VendaLivroServices vendaLivroServices = ServicesFactory.getVendaLivroServices();
            vendaLivroServices.addVendaLivro(vendaLivro);

            addRowToTable();

            //
            Integer quantidade = Integer.parseInt(jtfQuantidade.getText());
            livro.setEstoque(livro.getEstoque() - quantidade);
            livroServices.updateFieldsOfCliente(livro);

        } catch (ParseException ex)
        {
            ex.printStackTrace();
            System.out.println("ex" + ex);
        } catch (SQLException ex)
        {
            ex.printStackTrace();
            System.out.println("" + ex.getMessage());
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    public void addRowToTable()
    {
        try
        {
            VendaLivroServices vendaLivroServices = ServicesFactory.getVendaLivroServices();

            DefaultTableModel model = (DefaultTableModel) jtListaCompraVenda.getModel();
            model.getDataVector().removeAllElements();
            model.fireTableDataChanged();
            Object rowData[] = new Object[6];

            for (VendaLivro itemVendaLivro : vendaLivroServices.getAll())
            {
                rowData[0] = itemVendaLivro.getIdVendaLivro();
                rowData[1] = itemVendaLivro.getIdCliente();
                rowData[2] = itemVendaLivro.getIdLivro();
                rowData[3] = itemVendaLivro.getQtd();
                rowData[4] = itemVendaLivro.getSubTotal();
                rowData[5] = itemVendaLivro.getDataVenda();
                model.addRow(rowData);
            }
        } catch (SQLException ex)
        {
            JOptionPane.showInputDialog("Clientes não existem.");
        }
    }
    private void jtfDocClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfDocClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfDocClienteActionPerformed

    private void jbClienteOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbClienteOkActionPerformed

        try
        {
            if (!jtfDocCliente.getText().equals(""))
            {
                ClienteServices clienteServices = ServicesFactory.getClienteServices();
                Cliente client = clienteServices.getByDoc(jtfDocCliente.getText());

                if (!client.getNomeCliente().equals(""))
                {
                    jlCliente.setText("Cliente Ok");
                }
            } else
            {
                JOptionPane.showMessageDialog(this, "Insira o Documento do cliente.");
            }

        } catch (SQLException ex)
        {
            Logger.getLogger(jfCompraVenda.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jbClienteOkActionPerformed

    private void jbIsbnOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbIsbnOkActionPerformed

        LocalDate today = LocalDate.now();
        String data = today.toString();

        try
        {
            if (!jtfDocLivro.getText().equals(""))
            {
                LivroServices livroServices = ServicesFactory.getLivroServices();
                Livro livro = livroServices.getByDoc(jtfDocLivro.getText());

                if (!livro.getTitulo().equals(""))
                {
                    jlLivro.setText("Livro Ok");
                    jlValorUnidade.setText("" + livro.getPreco());
                    jtfQuantidade.setText("" + livro.getEstoque());
                    jlData.setText(today.toString());
                }
            } else
            {
                JOptionPane.showMessageDialog(this, "Insira o Documento do livro.");
            }
        } catch (SQLException ex)
        {
            Logger.getLogger(jfCompraVenda.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jbIsbnOkActionPerformed

    private void jbCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCalcularActionPerformed
        // TODO add your handling code here:

        if (!jtfQuantidade.getText().equals(""))
        {
            Double valor = Double.parseDouble(jlValorUnidade.getText());
            Integer quantidade = Integer.parseInt(jtfQuantidade.getText());
            Double valorFinal = valor * quantidade;

            jtfSubTotal.setText("" + valorFinal);
        } else
        {
            JOptionPane.showMessageDialog(this, "Insira quantidade.");
        }
    }//GEN-LAST:event_jbCalcularActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(jfCompraVenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(jfCompraVenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(jfCompraVenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(jfCompraVenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new jfCompraVenda().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbCalcular;
    private javax.swing.JButton jbClienteOk;
    private javax.swing.JButton jbIsbnOk;
    private javax.swing.JLabel jlCliente;
    private javax.swing.JLabel jlData;
    private javax.swing.JLabel jlLivro;
    private javax.swing.JLabel jlValorUnidade;
    private javax.swing.JTable jtListaCompraVenda;
    private javax.swing.JTextField jtfDocCliente;
    private javax.swing.JTextField jtfDocLivro;
    private javax.swing.JTextField jtfQuantidade;
    private javax.swing.JTextField jtfSubTotal;
    // End of variables declaration//GEN-END:variables
}
